# This file is from RAWR Agent - https://github.com/jeremykpark/rawr_agent
import report_creator as rc
import plotly.express as px
import json

# Generate a RAWR instant report using the code below
# made with Report Creator by Daren Race see documentation here: https://report-creator.readthedocs.io/en/latest/api.html

def generate_instant_report(json_str: str):
    #json_data = [json.loads(item) for item in json_data]
    # using key value comma-delimited string currently to work around json issues with AIQ function inputs
    values = json_str.split(",")
    keyvalues = {values[i]: values[i + 1] for i in range(0, len(values)- 1, 2)}

    
    # Create a report with various visualizations and metrics
    with rc.ReportCreator(
            title="New Instant Report",
            description="Custom report that could be triggered by an event",
            footer="Report created by <a href='https://github.com/jeremykpark/rawr_agent'>RAWR Agent</a> for <a href='https://docs.nvidia.com/agentiq/latest/index.html'>Nvidia AgentIQ</a> - Generated by <a href='https://github.com/darenr/report_creator'>Report Creator</a>",
            logo="img/t-rex.svg",
            ) as report:
                view = rc.Block(
                        rc.Group(
                                rc.Image("img/birthday-party-flyer.jpg", extra_css="max-width:200px;"),
                                rc.Group(
                                        rc.Text("<strong>Event Name:</strong> " + keyvalues.get("event_name", "Unknown")),
                                        rc.Text("<strong>Event Date:</strong> " + keyvalues.get("event_date", "Unknown")),
                                        rc.Text("<strong>Event Location:</strong> " + keyvalues.get("event_location", "Unknown")),
                                        rc.Text("<strong>Event DJ:</strong> " + keyvalues.get("event_dj", "Unknown")),                                        
                                        rc.Text("Raw Data: " + json_str),
                                ),
                        ),
                    rc.Heading("Report Creator Components Demo"),
                    rc.Text("These components are setup with demo information to demonstrate the capabilities of Report Creator."),
                    rc.Group(
                            rc.Metric(
                            heading="Answer to Life, The Universe, and Everything",
                            value="42",
                            ),
                            rc.Metric(
                            heading="Author",
                            value="Douglas Adams",
                            ),
                    ),
                    rc.Bar(px.data.medals_long(),
                            x="nation",
                            y="count",
                            dimension="medal",
                            label="Bar Chart - Olympic Medals",
                    ),
                    rc.Scatter(
                            px.data.iris(),
                            x="sepal_width",
                            y="sepal_length",
                            dimension="species",
                            marginal="histogram",
                            label="Scatter Plot - Iris",
                    ),
                    rc.Scatter(
                            px.data.iris(),
                            x="sepal_width",
                            y="sepal_length",
                            dimension="species",
                            marginal="histogram",
                            label="Scatter Plot - Iris",
                    ),
                )
    return report, view