# This file is from RAWR Agent - https://github.com/jeremykpark/rawr_agent
import report_creator as rc
import plotly.express as px

# Generate a RAWR monthly report using the code below
# made with Report Creator by Daren Race see documentation here: https://report-creator.readthedocs.io/en/latest/api.html

def generate_monthly_report(json_str: str):
      
# using key value comma-delimited string currently to work around json issues with AIQ function inputs
        
    with rc.ReportCreator(
            title="Monthly Report",
            description="A summary of the monthly activities. Generated on the first day of each month.",
            footer="Report created by <a href='https://github.com/jeremykpark/rawr_agent'>RAWR Agent</a> for <a href='https://docs.nvidia.com/agentiq/latest/index.html'>Nvidia AgentIQ</a> - Generated by <a href='https://github.com/darenr/report_creator'>Report Creator</a>",
            logo="img/t-rex.svg",
            ) as report:
                view = rc.Block(
                        rc.Group(
                                rc.Image("img/birthday-party-flyer.jpg", extra_css="max-width:200px;"),
                                rc.Group(
                                        rc.Text(json_str),
                                         rc.Text(json_str),
                                ),
                        ),
                    rc.Heading("Report Creator Components Demo"),
                    rc.Text("These components are setup with demo information to demonstrate the capabilities of Report Creator."),
                    rc.Text("Summary of the month"),
                    rc.Group(
                            rc.Metric(
                            heading="Total Events",
                            value="100",
                            ),
                            rc.Metric(
                            heading="Total Participants",
                            value="500",
                            ),
                    ),
                    rc.Bar(px.data.tips(),
                            x="day",
                            y="total_bill"
                            ),
                    )

    return report, view